version: 0.2

phases:
  build:
    commands:
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation \
          --distribution-id E2QK2HNW02TTR8 \
          --paths "/*"

      - echo "Validating CloudFront response"
      - curl -I https://d1cfnpuhm3esw5.cloudfront.net/index.html || exit 1

artifacts:
  files:
    - index.html
