version: 0.2

phases:
  build:
    commands:
      - echo "Uploading index.html to S3"
      - aws s3 cp index.html s3://mytestingbucekt/index.html
      - echo "Starting CloudFront cache invalidation"
      - aws cloudfront create-invalidation --distribution-id E3VZ7IHH20W172 --paths "/*"
      - echo "Verifying CloudFront URL"
      - curl -I https://dgpafv5ga7uij.cloudfront.net/index.html || exit 1

artifacts:
  files:
    - index.html
